### ISSUE TITLE
How to implement this on Antd design Pro

### ISSUE THREAD

**Issue by balmacefa** [mzohaibqc/antd-amplify-react#1]
How do I use those components in a Ant design Pro??

I try to modify the src\layouts\SecurityLayout.tsx file to implement it.
Does somebody have an explample file?

**Comment by mzohaibqc** [comment]
Amplify react has a different kind of implementation to hide protected routes. So you have to add logic to your components to return `null` if that should not be returned based on `authState` prop and actual content if should be rendered.

e.g.

```
<Authenticator hideDefault>
    <BasicLayout>
      <AuthFlow
        tabPosition="left"
        tabView
        signInFormProps={{
          hideSignUpLink: false,
          hideResetPasswordLink: false,
          usernameInputProps: {
            message: "Invalid username!"
          }
        }}
      />
      // Your custom components here
      <SignIn title="Sign In" formProps={{
        hideSignUpLink: false,
        hideResetPasswordLink: false,
        usernameInputProps: {
          message: 'Invalid username!'
        }
      }} />
      <SignUp />
      <RequireNewPassword />
      <ResetPassword />
      <ConfirmSignUp />
    </App> // only one child component will be and should be rendered based on props.authState and others will return `null`
  </Authenticator>
```

**Comment by balmacefa** [comment]
Thank you!
Justs for the record I found the conditional rendering documentation:

https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#manage-auth-state-and-conditional-app-rendering
